/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OpportunitiesIndexRouteImport } from './routes/opportunities.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as ServicesWellnessRouteImport } from './routes/services.wellness'
import { Route as ServicesTravelsRouteImport } from './routes/services.travels'
import { Route as ServicesTechnologyRouteImport } from './routes/services.technology'
import { Route as ServicesServicesRouteImport } from './routes/services.services'
import { Route as ServicesRozgarRouteImport } from './routes/services.rozgar'
import { Route as ServicesRishtaRouteImport } from './routes/services.rishta'
import { Route as ServicesPropertiesRouteImport } from './routes/services.properties'
import { Route as ServicesMediaRouteImport } from './routes/services.media'
import { Route as ServicesMartRouteImport } from './routes/services.mart'
import { Route as ServicesGyanRouteImport } from './routes/services.gyan'
import { Route as ServicesFoundationRouteImport } from './routes/services.foundation'
import { Route as ServicesFinanceRouteImport } from './routes/services.finance'
import { Route as ServicesDeliveryRouteImport } from './routes/services.delivery'
import { Route as OpportunitiesMerchantRouteImport } from './routes/opportunities.merchant'
import { Route as OpportunitiesInvestorRouteImport } from './routes/opportunities.investor'
import { Route as OpportunitiesConsumerRouteImport } from './routes/opportunities.consumer'
import { Route as OpportunitiesCareerRouteImport } from './routes/opportunities.career'
import { Route as AboutVisionRouteImport } from './routes/about.vision'
import { Route as AboutPhilosophyRouteImport } from './routes/about.philosophy'
import { Route as AboutNetworkRouteImport } from './routes/about.network'
import { Route as AboutMissionRouteImport } from './routes/about.mission'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesIndexRoute = OpportunitiesIndexRouteImport.update({
  id: '/opportunities/',
  path: '/opportunities/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesWellnessRoute = ServicesWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTravelsRoute = ServicesTravelsRouteImport.update({
  id: '/travels',
  path: '/travels',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesTechnologyRoute = ServicesTechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesServicesRoute = ServicesServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRozgarRoute = ServicesRozgarRouteImport.update({
  id: '/rozgar',
  path: '/rozgar',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesRishtaRoute = ServicesRishtaRouteImport.update({
  id: '/rishta',
  path: '/rishta',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesPropertiesRoute = ServicesPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMediaRoute = ServicesMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesMartRoute = ServicesMartRouteImport.update({
  id: '/mart',
  path: '/mart',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGyanRoute = ServicesGyanRouteImport.update({
  id: '/gyan',
  path: '/gyan',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFoundationRoute = ServicesFoundationRouteImport.update({
  id: '/foundation',
  path: '/foundation',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesFinanceRoute = ServicesFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDeliveryRoute = ServicesDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => ServicesRoute,
} as any)
const OpportunitiesMerchantRoute = OpportunitiesMerchantRouteImport.update({
  id: '/opportunities/merchant',
  path: '/opportunities/merchant',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesInvestorRoute = OpportunitiesInvestorRouteImport.update({
  id: '/opportunities/investor',
  path: '/opportunities/investor',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesConsumerRoute = OpportunitiesConsumerRouteImport.update({
  id: '/opportunities/consumer',
  path: '/opportunities/consumer',
  getParentRoute: () => rootRouteImport,
} as any)
const OpportunitiesCareerRoute = OpportunitiesCareerRouteImport.update({
  id: '/opportunities/career',
  path: '/opportunities/career',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutVisionRoute = AboutVisionRouteImport.update({
  id: '/about/vision',
  path: '/about/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutPhilosophyRoute = AboutPhilosophyRouteImport.update({
  id: '/about/philosophy',
  path: '/about/philosophy',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutNetworkRoute = AboutNetworkRouteImport.update({
  id: '/about/network',
  path: '/about/network',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutMissionRoute = AboutMissionRouteImport.update({
  id: '/about/mission',
  path: '/about/mission',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRouteWithChildren
  '/about/mission': typeof AboutMissionRoute
  '/about/network': typeof AboutNetworkRoute
  '/about/philosophy': typeof AboutPhilosophyRoute
  '/about/vision': typeof AboutVisionRoute
  '/opportunities/career': typeof OpportunitiesCareerRoute
  '/opportunities/consumer': typeof OpportunitiesConsumerRoute
  '/opportunities/investor': typeof OpportunitiesInvestorRoute
  '/opportunities/merchant': typeof OpportunitiesMerchantRoute
  '/services/delivery': typeof ServicesDeliveryRoute
  '/services/finance': typeof ServicesFinanceRoute
  '/services/foundation': typeof ServicesFoundationRoute
  '/services/gyan': typeof ServicesGyanRoute
  '/services/mart': typeof ServicesMartRoute
  '/services/media': typeof ServicesMediaRoute
  '/services/properties': typeof ServicesPropertiesRoute
  '/services/rishta': typeof ServicesRishtaRoute
  '/services/rozgar': typeof ServicesRozgarRoute
  '/services/services': typeof ServicesServicesRoute
  '/services/technology': typeof ServicesTechnologyRoute
  '/services/travels': typeof ServicesTravelsRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/about/': typeof AboutIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRouteWithChildren
  '/about/mission': typeof AboutMissionRoute
  '/about/network': typeof AboutNetworkRoute
  '/about/philosophy': typeof AboutPhilosophyRoute
  '/about/vision': typeof AboutVisionRoute
  '/opportunities/career': typeof OpportunitiesCareerRoute
  '/opportunities/consumer': typeof OpportunitiesConsumerRoute
  '/opportunities/investor': typeof OpportunitiesInvestorRoute
  '/opportunities/merchant': typeof OpportunitiesMerchantRoute
  '/services/delivery': typeof ServicesDeliveryRoute
  '/services/finance': typeof ServicesFinanceRoute
  '/services/foundation': typeof ServicesFoundationRoute
  '/services/gyan': typeof ServicesGyanRoute
  '/services/mart': typeof ServicesMartRoute
  '/services/media': typeof ServicesMediaRoute
  '/services/properties': typeof ServicesPropertiesRoute
  '/services/rishta': typeof ServicesRishtaRoute
  '/services/rozgar': typeof ServicesRozgarRoute
  '/services/services': typeof ServicesServicesRoute
  '/services/technology': typeof ServicesTechnologyRoute
  '/services/travels': typeof ServicesTravelsRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/about': typeof AboutIndexRoute
  '/opportunities': typeof OpportunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/services': typeof ServicesRouteWithChildren
  '/about/mission': typeof AboutMissionRoute
  '/about/network': typeof AboutNetworkRoute
  '/about/philosophy': typeof AboutPhilosophyRoute
  '/about/vision': typeof AboutVisionRoute
  '/opportunities/career': typeof OpportunitiesCareerRoute
  '/opportunities/consumer': typeof OpportunitiesConsumerRoute
  '/opportunities/investor': typeof OpportunitiesInvestorRoute
  '/opportunities/merchant': typeof OpportunitiesMerchantRoute
  '/services/delivery': typeof ServicesDeliveryRoute
  '/services/finance': typeof ServicesFinanceRoute
  '/services/foundation': typeof ServicesFoundationRoute
  '/services/gyan': typeof ServicesGyanRoute
  '/services/mart': typeof ServicesMartRoute
  '/services/media': typeof ServicesMediaRoute
  '/services/properties': typeof ServicesPropertiesRoute
  '/services/rishta': typeof ServicesRishtaRoute
  '/services/rozgar': typeof ServicesRozgarRoute
  '/services/services': typeof ServicesServicesRoute
  '/services/technology': typeof ServicesTechnologyRoute
  '/services/travels': typeof ServicesTravelsRoute
  '/services/wellness': typeof ServicesWellnessRoute
  '/about/': typeof AboutIndexRoute
  '/opportunities/': typeof OpportunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/faq'
    | '/services'
    | '/about/mission'
    | '/about/network'
    | '/about/philosophy'
    | '/about/vision'
    | '/opportunities/career'
    | '/opportunities/consumer'
    | '/opportunities/investor'
    | '/opportunities/merchant'
    | '/services/delivery'
    | '/services/finance'
    | '/services/foundation'
    | '/services/gyan'
    | '/services/mart'
    | '/services/media'
    | '/services/properties'
    | '/services/rishta'
    | '/services/rozgar'
    | '/services/services'
    | '/services/technology'
    | '/services/travels'
    | '/services/wellness'
    | '/about/'
    | '/opportunities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/faq'
    | '/services'
    | '/about/mission'
    | '/about/network'
    | '/about/philosophy'
    | '/about/vision'
    | '/opportunities/career'
    | '/opportunities/consumer'
    | '/opportunities/investor'
    | '/opportunities/merchant'
    | '/services/delivery'
    | '/services/finance'
    | '/services/foundation'
    | '/services/gyan'
    | '/services/mart'
    | '/services/media'
    | '/services/properties'
    | '/services/rishta'
    | '/services/rozgar'
    | '/services/services'
    | '/services/technology'
    | '/services/travels'
    | '/services/wellness'
    | '/about'
    | '/opportunities'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/faq'
    | '/services'
    | '/about/mission'
    | '/about/network'
    | '/about/philosophy'
    | '/about/vision'
    | '/opportunities/career'
    | '/opportunities/consumer'
    | '/opportunities/investor'
    | '/opportunities/merchant'
    | '/services/delivery'
    | '/services/finance'
    | '/services/foundation'
    | '/services/gyan'
    | '/services/mart'
    | '/services/media'
    | '/services/properties'
    | '/services/rishta'
    | '/services/rozgar'
    | '/services/services'
    | '/services/technology'
    | '/services/travels'
    | '/services/wellness'
    | '/about/'
    | '/opportunities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AboutMissionRoute: typeof AboutMissionRoute
  AboutNetworkRoute: typeof AboutNetworkRoute
  AboutPhilosophyRoute: typeof AboutPhilosophyRoute
  AboutVisionRoute: typeof AboutVisionRoute
  OpportunitiesCareerRoute: typeof OpportunitiesCareerRoute
  OpportunitiesConsumerRoute: typeof OpportunitiesConsumerRoute
  OpportunitiesInvestorRoute: typeof OpportunitiesInvestorRoute
  OpportunitiesMerchantRoute: typeof OpportunitiesMerchantRoute
  AboutIndexRoute: typeof AboutIndexRoute
  OpportunitiesIndexRoute: typeof OpportunitiesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/': {
      id: '/opportunities/'
      path: '/opportunities'
      fullPath: '/opportunities/'
      preLoaderRoute: typeof OpportunitiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/wellness': {
      id: '/services/wellness'
      path: '/wellness'
      fullPath: '/services/wellness'
      preLoaderRoute: typeof ServicesWellnessRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/travels': {
      id: '/services/travels'
      path: '/travels'
      fullPath: '/services/travels'
      preLoaderRoute: typeof ServicesTravelsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/technology': {
      id: '/services/technology'
      path: '/technology'
      fullPath: '/services/technology'
      preLoaderRoute: typeof ServicesTechnologyRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/services': {
      id: '/services/services'
      path: '/services'
      fullPath: '/services/services'
      preLoaderRoute: typeof ServicesServicesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rozgar': {
      id: '/services/rozgar'
      path: '/rozgar'
      fullPath: '/services/rozgar'
      preLoaderRoute: typeof ServicesRozgarRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/rishta': {
      id: '/services/rishta'
      path: '/rishta'
      fullPath: '/services/rishta'
      preLoaderRoute: typeof ServicesRishtaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/properties': {
      id: '/services/properties'
      path: '/properties'
      fullPath: '/services/properties'
      preLoaderRoute: typeof ServicesPropertiesRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/media': {
      id: '/services/media'
      path: '/media'
      fullPath: '/services/media'
      preLoaderRoute: typeof ServicesMediaRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mart': {
      id: '/services/mart'
      path: '/mart'
      fullPath: '/services/mart'
      preLoaderRoute: typeof ServicesMartRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/gyan': {
      id: '/services/gyan'
      path: '/gyan'
      fullPath: '/services/gyan'
      preLoaderRoute: typeof ServicesGyanRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/foundation': {
      id: '/services/foundation'
      path: '/foundation'
      fullPath: '/services/foundation'
      preLoaderRoute: typeof ServicesFoundationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/finance': {
      id: '/services/finance'
      path: '/finance'
      fullPath: '/services/finance'
      preLoaderRoute: typeof ServicesFinanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/delivery': {
      id: '/services/delivery'
      path: '/delivery'
      fullPath: '/services/delivery'
      preLoaderRoute: typeof ServicesDeliveryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/opportunities/merchant': {
      id: '/opportunities/merchant'
      path: '/opportunities/merchant'
      fullPath: '/opportunities/merchant'
      preLoaderRoute: typeof OpportunitiesMerchantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/investor': {
      id: '/opportunities/investor'
      path: '/opportunities/investor'
      fullPath: '/opportunities/investor'
      preLoaderRoute: typeof OpportunitiesInvestorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/consumer': {
      id: '/opportunities/consumer'
      path: '/opportunities/consumer'
      fullPath: '/opportunities/consumer'
      preLoaderRoute: typeof OpportunitiesConsumerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/opportunities/career': {
      id: '/opportunities/career'
      path: '/opportunities/career'
      fullPath: '/opportunities/career'
      preLoaderRoute: typeof OpportunitiesCareerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/vision': {
      id: '/about/vision'
      path: '/about/vision'
      fullPath: '/about/vision'
      preLoaderRoute: typeof AboutVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/philosophy': {
      id: '/about/philosophy'
      path: '/about/philosophy'
      fullPath: '/about/philosophy'
      preLoaderRoute: typeof AboutPhilosophyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/network': {
      id: '/about/network'
      path: '/about/network'
      fullPath: '/about/network'
      preLoaderRoute: typeof AboutNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/mission': {
      id: '/about/mission'
      path: '/about/mission'
      fullPath: '/about/mission'
      preLoaderRoute: typeof AboutMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesDeliveryRoute: typeof ServicesDeliveryRoute
  ServicesFinanceRoute: typeof ServicesFinanceRoute
  ServicesFoundationRoute: typeof ServicesFoundationRoute
  ServicesGyanRoute: typeof ServicesGyanRoute
  ServicesMartRoute: typeof ServicesMartRoute
  ServicesMediaRoute: typeof ServicesMediaRoute
  ServicesPropertiesRoute: typeof ServicesPropertiesRoute
  ServicesRishtaRoute: typeof ServicesRishtaRoute
  ServicesRozgarRoute: typeof ServicesRozgarRoute
  ServicesServicesRoute: typeof ServicesServicesRoute
  ServicesTechnologyRoute: typeof ServicesTechnologyRoute
  ServicesTravelsRoute: typeof ServicesTravelsRoute
  ServicesWellnessRoute: typeof ServicesWellnessRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesDeliveryRoute: ServicesDeliveryRoute,
  ServicesFinanceRoute: ServicesFinanceRoute,
  ServicesFoundationRoute: ServicesFoundationRoute,
  ServicesGyanRoute: ServicesGyanRoute,
  ServicesMartRoute: ServicesMartRoute,
  ServicesMediaRoute: ServicesMediaRoute,
  ServicesPropertiesRoute: ServicesPropertiesRoute,
  ServicesRishtaRoute: ServicesRishtaRoute,
  ServicesRozgarRoute: ServicesRozgarRoute,
  ServicesServicesRoute: ServicesServicesRoute,
  ServicesTechnologyRoute: ServicesTechnologyRoute,
  ServicesTravelsRoute: ServicesTravelsRoute,
  ServicesWellnessRoute: ServicesWellnessRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AboutMissionRoute: AboutMissionRoute,
  AboutNetworkRoute: AboutNetworkRoute,
  AboutPhilosophyRoute: AboutPhilosophyRoute,
  AboutVisionRoute: AboutVisionRoute,
  OpportunitiesCareerRoute: OpportunitiesCareerRoute,
  OpportunitiesConsumerRoute: OpportunitiesConsumerRoute,
  OpportunitiesInvestorRoute: OpportunitiesInvestorRoute,
  OpportunitiesMerchantRoute: OpportunitiesMerchantRoute,
  AboutIndexRoute: AboutIndexRoute,
  OpportunitiesIndexRoute: OpportunitiesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
